add: Basic md files and ESLint set up completed
dscnitrourkela/project-icecream pull request #30
Opened 2021-08-29 19:51 UTC by Sonakshi1901

2021-08-30 21:49 UTC, abhibhaw requested changes
Readme needs a lot of changes!!

2021-08-30 21:49 UTC, abhibhaw commented on README.md
> +  <a href="https://github.com/dscnitrourkela/project-oregano">
Never copy paste aankh band krke 🤣

2021-08-31 04:05 UTC, Sonakshi1901 commented on README.md
> +  <a href="https://github.com/dscnitrourkela/project-oregano">
Thanks for pointing that out, bhaiya! I did not notice it then. The changes are made.

2021-08-31 06:16 UTC, riteshsp2000 commented
Hey @Sonakshi1901 quite a few changes required, ill list them all here.
- The title in README, is HackNITR, we need to be Frameboi.
- Update all the links at the starting part.
- In the table of contents, create a section for HackNITR and add the about project content right up there.
- And in the about project section describe this project and not hacknitr :|
- Built with, only the technologies are mentioned, add the links to all their websites as well
---

- Add keywords and proper description in package.json
- Not all essential files/folders are included in gitignore. use [gitignore.io](https://gitignore.io) generate them and use it for eslint and prettier as well. A few keywords for generating: gatsby node firebase yarn (add any extra if needed)
---

- We will be using tailwing and styled components, set those up as well (using twin macro and all)
- Checkout the gatsby config page, quite a few things are mentioned there, so make sure you set up most of those things and if need be others as well.

2021-08-31 08:11 UTC, Sonakshi1901 commented
Ok, got it.

2021-08-31 08:15 UTC, Sonakshi1901 commented
@riteshsp2000 Do we use the HackNITR logo or some other picture?

2021-08-31 11:45 UTC, Sonakshi1901 commented
@riteshsp2000 Do let me know if I have to make any more changes in the gatsby-config file.

2021-08-31 12:41 UTC, abhibhaw reviewed
repo cover is also missing

2021-08-31 12:41 UTC, abhibhaw commented on README.md
> +        <li><a href="#hackNITR">HackNITR 3.0</a></li>
This href is wrong

2021-08-31 12:41 UTC, abhibhaw commented on README.md
> +        <li><a href="#contribution-guidelines">Contribution guidelines</a></li>
this too wrong

2021-08-31 15:04 UTC, Sonakshi1901 commented on README.md
> +        <li><a href="#contribution-guidelines">Contribution guidelines</a></li>
Is it contribution guidelines?

2021-08-31 15:06 UTC, Sonakshi1901 commented
> repo cover is also missing

@abhibhaw repo cover is in the images folder.

2021-08-31 15:07 UTC, Sonakshi1901 commented on README.md
> +        <li><a href="#hackNITR">HackNITR 3.0</a></li>
Ok

2021-08-31 16:40 UTC, DesignrKnight commented on README.md
> +NOTE 2: Please abide by the [Code of Conduct](https://github.com/dscnitrourkela/project-guava-web/blob/master/CODE_OF_CONDUCT.md).
Links need correction

2021-08-31 16:40 UTC, DesignrKnight commented on README.md
> +## Checkout into the project client directory
Double check if this step is needed.

2021-08-31 16:42 UTC, Sonakshi1901 commented on README.md
> +## Checkout into the project client directory
Ok

2021-08-31 16:42 UTC, Sonakshi1901 commented on README.md
> +NOTE 2: Please abide by the [Code of Conduct](https://github.com/dscnitrourkela/project-guava-web/blob/master/CODE_OF_CONDUCT.md).
Ok

2021-09-02 18:30 UTC, riteshsp2000 approved these changes

2021-09-02 18:30 UTC, merged